# Generated by Django 3.0.8 on 2020-07-29 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberMasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bMaster', models.CharField(max_length=100, verbose_name='Фамилия или Имя или Ник')),
                ('bMaster_text', models.TextField(blank=True, verbose_name='Описание мастера')),
                ('bDateBegin', models.DateField(blank=True, editable=False, null=True, verbose_name='Служебное поле дата начала отсутствия')),
                ('bDateEnd', models.DateField(blank=True, editable=False, null=True, verbose_name='Служебное поле дата окончания отсутствия')),
            ],
            options={
                'db_table': 'barber_masters',
            },
        ),
        migrations.CreateModel(
            name='BarberNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bTitleNews', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('bTextNews', models.TextField(verbose_name='Текст новости')),
                ('bNewsDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('bNewsImage', models.ImageField(blank=True, upload_to='imgnews/', verbose_name='Картинка новости')),
            ],
            options={
                'db_table': 'barber_news',
                'ordering': ['bNewsDate'],
            },
        ),
        migrations.CreateModel(
            name='BarberService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bService', models.CharField(max_length=200, verbose_name='Наименование услуги')),
                ('bPrice', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена услуги')),
                ('bService_text', models.TextField(blank=True, verbose_name='Описание услуги')),
            ],
            options={
                'db_table': 'barber_service',
            },
        ),
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bTime', models.TimeField(verbose_name='Время услуги')),
                ('bTimeStatus', models.CharField(blank=True, editable=False, max_length=10, verbose_name='СлужебноеПоле')),
            ],
            options={
                'db_table': 'barber_service_time',
                'ordering': ['bTime'],
            },
        ),
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bOrderCreateDate', models.DateField(verbose_name='Дата создания')),
                ('bOrderStatus', models.BooleanField(default=False)),
                ('bOrderMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relOrderMaster', to='barberback.BarberMasters')),
                ('bOrderService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relOrderService', to='barberback.BarberService')),
                ('bOrderTimeService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relOrderServiceTime', to='barberback.ServiceTime')),
                ('bOrderUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relOrderUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'barber_user_orders',
                'ordering': ['bOrderCreateDate'],
            },
        ),
        migrations.CreateModel(
            name='MasterTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bDateBegin', models.DateField(verbose_name='Дата начала отсутствия')),
                ('bDateEnd', models.DateField(verbose_name='Дата окончания отсутствия')),
                ('bTimeMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reltimemaster', to='barberback.BarberMasters')),
            ],
            options={
                'db_table': 'master_time',
            },
        ),
        migrations.CreateModel(
            name='BarberUserSendNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bSend', models.BooleanField(default=False)),
                ('bNews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bNews', to='barberback.BarberNews')),
                ('bNewsUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bNewsUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'barber_sendNews',
            },
        ),
        migrations.CreateModel(
            name='BarberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barber_Phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Телефон пользователя')),
                ('Barber_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'barber_profile',
            },
        ),
    ]
